//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int id_factura { get; set; }
        public System.DateTime fecha { get; set; }
        public string dni_cliente { get; set; }
        public Nullable<int> id_reparacion { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Reparaciones Reparaciones { get; set; }
    }
}
